### ISSUE TITLE
pastebin run Q8ah3K9S

### ISSUE THREAD

**Issue by lukebjones** [jaranvil/CraftNanny#12]
You don't have to get it and run it. You could change your setup page to have this

**Comment by jaranvil** [comment]
Oh that's awesome, I didn't know that was a command

**Comment by demethan** [comment]
Tested.. it works as is. 
you may change the website

**Comment by jaranvil** [comment]
what does the file name default to?

**Comment by demethan** [comment]
the filename doesn't stay there. if you require install to be there, add it to your script.

**Comment by lukebjones** [comment]
Yeah if you wanted the 'install' file to be saved on the computer post-installation you could get it to save itself. I just think it looks a lot cleaner running only one command.
